In [2]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import tree
import joblib

In [2]:
df = pd.read_csv('vgsales.csv')
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [3]:
df.shape

(16598, 11)

In [4]:
df.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [5]:
df.values

array([[1, 'Wii Sports', 'Wii', ..., 3.77, 8.46, 82.74],
       [2, 'Super Mario Bros.', 'NES', ..., 6.81, 0.77, 40.24],
       [3, 'Mario Kart Wii', 'Wii', ..., 3.79, 3.31, 35.82],
       ...,
       [16598, 'SCORE International Baja 1000: The Official Game', 'PS2',
        ..., 0.0, 0.0, 0.01],
       [16599, 'Know How 2', 'DS', ..., 0.0, 0.0, 0.01],
       [16600, 'Spirits & Spells', 'GBA', ..., 0.0, 0.0, 0.01]],
      dtype=object)

In [3]:
music_data = pd.read_csv('music.csv')

In [4]:
print(music_data)

    age  gender      genre
0    20       1     HipHop
1    23       1     HipHop
2    25       1     HipHop
3    26       1       Jazz
4    29       1       Jazz
5    30       1       Jazz
6    31       1  Classical
7    33       1  Classical
8    37       1  Classical
9    20       0      Dance
10   21       0      Dance
11   25       0      Dance
12   26       0   Acoustic
13   27       0   Acoustic
14   30       0   Acoustic
15   31       0  Classical
16   34       0  Classical
17   35       0  Classical

In [5]:
X = music_data.drop(columns = ['genre'])
Y = music_data['genre']

In [6]:
X

    age  gender
0    20       1
1    23       1
2    25       1
3    26       1
4    29       1
5    30       1
6    31       1
7    33       1
8    37       1
9    20       0
10   21       0
11   25       0
12   26       0
13   27       0
14   30       0
15   31       0
16   34       0
17   35       0

In [7]:
Y

0        HipHop
1        HipHop
2        HipHop
3          Jazz
4          Jazz
5          Jazz
6     Classical
7     Classical
8     Classical
9         Dance
10        Dance
11        Dance
12     Acoustic
13     Acoustic
14     Acoustic
15    Classical
16    Classical
17    Classical
Name: genre, dtype: object

In [8]:
print(Y.values)
print(X.values)
print(X.values[4][0])
print(type(Y.values))
print(type(X.values))

['HipHop' 'HipHop' 'HipHop' 'Jazz' 'Jazz' 'Jazz' 'Classical' 'Classical'
 'Classical' 'Dance' 'Dance' 'Dance' 'Acoustic' 'Acoustic' 'Acoustic'
 'Classical' 'Classical' 'Classical']
[[20  1]
 [23  1]
 [25  1]
 [26  1]
 [29  1]
 [30  1]
 [31  1]
 [33  1]
 [37  1]
 [20  0]
 [21  0]
 [25  0]
 [26  0]
 [27  0]
 [30  0]
 [31  0]
 [34  0]
 [35  0]]
29
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [12]:
model = DecisionTreeClassifier()
model.fit(X.values,Y.values)
predictions = model.predict([ [21, 1], [22, 0], [56, 1] ])
predictions

array(['HipHop', 'Dance', 'Classical'], dtype=object)

In [91]:
X = music_data.drop(columns = ['genre'])
Y = music_data['genre']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

In [92]:
model2 = DecisionTreeClassifier()
model2.fit(X_train.values,Y_train.values)
predictions2 = model2.predict(X_test.values)

score = accuracy_score(Y_test.values, predictions2)
score

1.0

In [205]:
print (X_train)
print (X_test)

    age  gender
12   26       0
10   21       0
17   35       0
0    20       1
9    20       0
11   25       0
3    26       1
15   31       0
7    33       1
13   27       0
5    30       1
6    31       1
4    29       1
16   34       0
    age  gender
14   30       0
8    37       1
2    25       1
1    23       1

In [200]:
X = music_data.drop(columns = ['genre'])
y = music_data['genre']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

model2 = DecisionTreeClassifier()
model2.fit(X_train.values,Y_train.values)
predictions2 = model2.predict(X_test.values)

score = accuracy_score(Y_test.values, predictions2)
score

0.75

In [15]:
joblib.dump(model2, 'music.recommender.joblib')

['music.recommender.joblib']

In [16]:
model = joblib.load('music.recommender.joblib')
predictions = model.predict([ [21, 1]])
predictions

array(['HipHop'], dtype=object)

In [17]:
X = music_data.drop(columns = ['genre'])
Y = music_data['genre']

model = DecisionTreeClassifier()
model.fit(X.values,Y.values)

tree.export_graphviz(model, out_file = 'music recomender.dot', 
                    feature_names = ['age', 'gender'], 
                    class_names = sorted(y.unique()), 
                    label = 'all',
                    rounded = True,
                    filled = True)

In [18]:
#NetwrokX read_dot
#graphvizs ow software maybe?    can install through anaconda
#!conda install graphviz       in terminal maybe 
#linear regression 
#logistic regression
# using game stats to predict something like win rate maybe?
#look up graphviz on anaconda